apiVersion: apps/v1
kind: Deployment
metadata:
  name: rv-review-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rv-review
  template:
    metadata:
      labels:
        app: rv-review
    spec:
      containers:
        - image: anzeha/rv-review
          name: rv-review
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://surus.db.elephantsql.com/tethyexn
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: tethyexn
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD_RV_REVIEW
            - name: KUMULUZEE_DATASOURCES0_POOL_MAX-SIZE
              value: "1"
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: rv-review
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: rv-review
