kumuluzee:
  name: rv-review-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    consul:
      agent: http://consul-server:8500
  discovery:
    cluster: 1
    consul:
      agent: http://consul-server:8500
  datasources:
    - jndi-name: jdbc/RvReviewDS
      connection-url: jdbc:postgresql://localhost:5434/rv_reviews
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RvReviewDS
  metrics:
    web-instrumentation:
      - name: rv-review-endpoint
        url-pattern: /v1/reviews/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="comments">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="ad58b2f1-ae55-491f-be39-341b36974574-ls.logit.io"
                                port="12895" protocol="udp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info" />
                                    <AppenderRef ref="logstash" level="trace" />
                                </Root>
                            </Loggers>
                        </Configuration>'
  rest-client:
    registrations:
      - class: rv-processing-api
        url: http://localhost:8082/v1
        read-timeout: 5000
  streaming:
    kafka:
      producer:
        bootstrap-servers: ark-01.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: newer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        sasl-jaas-config:
rest-properties:
  maintenance-mode: false
  broken: false
  fallback: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key:
